### ISSUE TITLE
Would you please provide UR10 pkg  so  I can simulate with your arm admittance controller?

### ISSUE THREAD

**Issue by 1508912767** [nbfigueroa/arm_admittance_controller#1]
Hi,

I just want to use admittance controller with my ur5 robot，so I change the ros pkg ridgeback with admittance control，but there so many diffirence between ur5 alone and ur5_and_ridgeback.

so can you tell me how to do this OR provide me UR10 pkg can work with arm_admittance_controller?

Thank you very much!

**Comment by nbfigueroa** [comment]
Hi! I know there are so many differences! That's why I created this package! Actually, my UR10 is mounted on another platform which is private right now, so cannot share it. But I can tell you how to use  arm_admittance_controller package, all you need is to read from three topics: 
``<arg name="POSE_TOPIC_ARM"           default="/UR10arm/ee_pose"/>
<arg name="TWIST_TOPIC_ARM"          default="/UR10arm/ee_twist"/> 
<arg name="WRENCH_EXT_TOPIC_ARM" default="/robotiq_force_torque_wrench_filtered"/>  
``
which correspond to the end-effector pose, velocity and force/torque readings. To get the pose and velocity you need to compute the forward kinematics from the joint states of the robot, I have that implemented for the UR10 here: https://github.com/nbfigueroa/robot_kinematics
In the code you can see the message types, etc. 

The arm_admittance_controller package will then output the desired velocity as a twist message:
`` 
<arg name="CMD_TOPIC_ARM" `default="/arm/twist_controller/command_twist"/>
``
This should be sent to an IK-solver. For my project I use this package:
https://github.com/ipa320/cob_control/tree/kinetic_dev/cob_twist_controller

I also have an IK solver in https://github.com/nbfigueroa/robot_kinematics but haven't tested it for a UR robot.. it should work though. 

Hope this helps.

**Comment by 1508912767** [comment]
Thanks for your Selfless devotion，actually，according to your arm admittance pkg，I have modified some code and now it can work with my UR5 in the gazebo，next I will use it in real UR5 robot，it is very helpful to see your way and code，thank you very much！

**Comment by 1508912767** [comment]
> Hi! I know there are so many differences! That's why I created this package! Actually, my UR10 is mounted on another platform which is private right now, so cannot share it. But I can tell you how to use arm_admittance_controller package, all you need is to read from three topics:
> `<arg name="POSE_TOPIC_ARM" default="/UR10arm/ee_pose"/> <arg name="TWIST_TOPIC_ARM" default="/UR10arm/ee_twist"/> <arg name="WRENCH_EXT_TOPIC_ARM" default="/robotiq_force_torque_wrench_filtered"/> `
> which correspond to the end-effector pose, velocity and force/torque readings. To get the pose and velocity you need to compute the forward kinematics from the joint states of the robot, I have that implemented for the UR10 here: https://github.com/nbfigueroa/robot_kinematics
> In the code you can see the message types, etc.
> 
> The arm_admittance_controller package will then output the desired velocity as a twist message:
> `` <arg name="CMD_TOPIC_ARM" `default="/arm/twist_controller/command_twist"/> ``
> This should be sent to an IK-solver. For my project I use this package:
> https://github.com/ipa320/cob_control/tree/kinetic_dev/cob_twist_controller
> 
> I also have an IK solver in https://github.com/nbfigueroa/robot_kinematics but haven't tested it for a UR robot.. it should work though.
> 
> Hope this helps.

Thanks for your Selfless devotion，actually，according to your arm admittance pkg，I have modified some code and now it can work with my UR5 in the gazebo，next I will use it in real UR5 robot，it is very helpful to see your way and code，thank you very much！

**Comment by nbfigueroa** [comment]
Great! Good luck!
